import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        /**
         * Generated by UI Colors, the main color is #74a277, corresponding to the character's clothing.
         * @See {@link https://uicolors.app/create}
         */
        amulet: {
          '50': '#f2f7f2',
          '100': '#e0ecdf',
          '200': '#c2d9c1',
          '300': '#98bd99',
          '400': '#74a277',
          '500': '#4a7f4f',
          '600': '#37643c',
          '700': '#2c5031',
          '800': '#25402a',
          '900': '#1f3522',
          '950': '#111d13',
        },
      },
      maxWidth: {
        'screen-minus-px-4': 'calc(100vw - 32px)',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
export default config;
